

GET http://localhost:8000/

###

#---- Restaurant---#
###
GET http://localhost:8000/restaurants
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4Mzc3MDE1fQ.WdQae4Oauv8FVh2VWKilOBhAGspbQdNjT_2BiRKSqvw


###
POST http://localhost:8000/restaurants
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjk1NjY1fQ.iMfw1eyQ8ehIkfoNG1WnkNRC-q_5dXnm584CE4C76aA
Content-Type: application/json

{
    "name": "Highlands",
    "address": "123 Kutus",
    "zip": 10100,
    "cityId": 6,
    "created_at": "2024-06-13",
    "updated_at": "2024-06-13"
}
###
PUT http://localhost:8000/restaurants/15
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjc1MjU4fQ.ZrN66hqwDoqnVo1tGmgHivVBjDuqc6xqJ_KEZfi0qms
Content-Type: application/json

{
    "name": "Hillton"
}
###
DELETE http://localhost:8000/restaurants/15
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjk1NjY1fQ.iMfw1eyQ8ehIkfoNG1WnkNRC-q_5dXnm584CE4C76aA

#---------------------- Users- token!!!-------------------#
###
GET http://localhost:8000/user-details/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjk1NjY1fQ.iMfw1eyQ8ehIkfoNG1WnkNRC-q_5dXnm584CE4C76aA

###--- admin
# GET https://restaurant-mngt.azurewebsites.net/users
GET http://localhost:8000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###--- user invalid token
GET https://restaurant-mngt.azurewebsites.net/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MTgyMDMwODd9.DiokaSe5S_G_luHpOiHnaiS9hVUZu4tol3_WVySTxjc


###
### POST https://restaurant-mngt.azurewebsites.net/register
POST http://localhost:8000/register
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "password",
    "role": "admin"
}

### ----------------------- role admin Login -----------------------------#
###
##POST https://restaurant-mngt.azurewebsites.net/login
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "password"
}

### ----------------------- role user Login -----------------------------#
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "passkey"
}

# ### ------------update password-----------------#
# PUT http://localhost:8000/update-password
# Content-Type: application/json

# {
#     "email": "example@gmail.com",
#     "password": "password"
# }

###
PUT http://localhost:8000/users/11
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjk1NjY1fQ.iMfw1eyQ8ehIkfoNG1WnkNRC-q_5dXnm584CE4C76aA
Content-Type: application/json

{
    "firstName": "Alexa"
}
###
DELETE http://localhost:8000/users/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjc1MjU4fQ.ZrN66hqwDoqnVo1tGmgHivVBjDuqc6xqJ_KEZfi0qms


#---- Orders---#
###
GET http://localhost:8000/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjc1MjU4fQ.ZrN66hqwDoqnVo1tGmgHivVBjDuqc6xqJ_KEZfi0qms

###
GET http://localhost:8000/order-details/51
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjc1MjU4fQ.ZrN66hqwDoqnVo1tGmgHivVBjDuqc6xqJ_KEZfi0qms

###

POST http://localhost:8000/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "restaurantId": "3",
    "estimatesDeliveryTime": "2024-06-06",
    "actualDeliveryTime": "2024-06-06",
    "deliveryAddressId": "Kutus",
    "userId": 3,
    "driverId": 2,
    "price": 1000,
    "discount": 250,
    "finalPrice": 750,
    "comment": "great deal",
    "createdAt": "2024-06-06",
    "updatedAt": "2024-06-06"
}

###
PUT http://localhost:8000/orders/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "price": "1200"
}
###
DELETE http://localhost:8000/orders/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


#---- States---#
###
GET http://localhost:8000/states
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


###

POST http://localhost:8000/states
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "Nairobi",
    "code": "10100"
}

###
PUT http://localhost:8000/states/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "Nakuru"
}
###
DELETE http://localhost:8000/states/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


#---- Menu item---#
###
GET http://localhost:8000/menu-items
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


###

POST http://localhost:8000/menu-items
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "pizza",
    "restaurant_id": 2,
    "category_id": 1,
    "description": "medium size pizza",
    "ingredients": "flour, cheese, tomato",
    "price": 1000,
    "active": true,
    "createdAt": "2024-06-06",
    "updatedAt": "2024-06-06"
}

###
PUT http://localhost:8000/menu-items/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "pizza",
    "description": "medium size pizza",
    "ingredients": "flour, cheese, tomato",
    "price": 1000
}
###
DELETE http://localhost:8000/menu-items/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


#---- Category---#
###
GET http://localhost:8000/categories 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###

POST http://localhost:8000/categories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "snacks"
}

###
PUT http://localhost:8000/categories/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "soft drinks"
}
###
DELETE http://localhost:8000/categories/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


#---- Comments---#
###
GET http://localhost:8000/comments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


###

POST http://localhost:8000/comments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "orderId": 1,
    "userId": 2,
    "commentText": "Great",
    "isComplaint": true,
    "isPraise": false,
    "createdAt": "2024-06-06",
    "updatedAt": "2024-06-06"
}
###
PUT http://localhost:8000/comments/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "commentsText": "Good"
}
###
DELETE http://localhost:8000/comments/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

#---- Address---#
###
GET http://localhost:8000/addresses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###

POST http://localhost:8000/addresses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "streetAddress1": 1,
    "streetAddress2": 2,
    "zipCode": 20210,
    "deliveryInstructions": "free",
    "userId": 2,
    "cityId": 3,
    "createdAt": "2024-06-06",
    "updatedAt": "2024-06-06"
}

###
PUT http://localhost:8000/addresses/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "fullname": "Alexa"
}
###
DELETE http://localhost:8000/addresses/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

#---- City---#
###
GET http://localhost:8000/cities 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###

POST http://localhost:8000/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "Nakuru",
    "stateId": 2
}

###
PUT http://localhost:8000/cities/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "Nairobi"
}
###
DELETE http://localhost:8000/cities/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

#---- Order menu item---#
###
GET http://localhost:8000/order-menu-items 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###

POST http://localhost:8000/order-menu-items
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "order_id": 5,
    "menu_item_id": 5,
    "quantity": 5,
    "itemPrice": 1000,
    "price": 2000,
    "comment": "great deal"
}

###
PUT http://localhost:8000/order-menu-items/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "quantity": 3,
    "price": 3000
}
###
DELETE http://localhost:8000/order-menu-items/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

#---- Status catalog---#
###
GET http://localhost:8000/status-catalogs 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###

POST http://localhost:8000/status-catalogs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "Pending"
}

###
PUT http://localhost:8000/status-catalogs/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "name": "Delivered"
}
###
DELETE http://localhost:8000/status-catalogs/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

#---- driver---#
###
GET http://localhost:8000/drivers 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###

POST http://localhost:8000/drivers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "carMake": "Toyota",
    "carModel": "Vitz",
    "carYear": 2010,
    "userId": 2,
    "online": true,
    "delivering": true,
    "createdAt": "2024-06-06",
    "updatedAt": "2024-06-06"
}

###
PUT http://localhost:8000/drivers/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "online": false,
    "delivering": false
}
###
DELETE http://localhost:8000/drivers/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


###
GET http://localhost:8000/drivers-with-address/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


#---- Restaurant owner---#
###
GET http://localhost:8000/restaurant-owners 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###

POST http://localhost:8000/restaurant-owners
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "restaurantId": 2,
    "ownerId": 2
}

###
PUT http://localhost:8000/restaurant-owners/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "ownerId": 3
}
###
DELETE http://localhost:8000/restaurant-owners/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

#---- Order status---#
###
GET http://localhost:8000/order-status 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###

POST http://localhost:8000/order-status
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "orderId": 5,
    "statusCatalogId": 1,
    "createdAt": "2024-06-08"
}

###
PUT http://localhost:8000/order-status/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
Content-Type: application/json

{
    "createdAt": "2024-06-07"
}
###
DELETE http://localhost:8000/order-status/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


#-------------------------- Users Register --------------------#
###
POST https://restaurant-mngt.azurewebsites.net/register
Content-Type: application/json

{
    "email": "alvert@gmail.com",
    "password": "1234",
    "firstName": "Alveres",
    "lastName": "Martin",
    "phone": "+25477361254",
    "createdAt": "2024-06-12",
    "updatedAt": "2024-06-12"
}



### ----------------------- Users delete -----------------------------#
DELETE https://restaurant-mngt.azurewebsites.net
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###
GET https://restaurant-mngt.azurewebsites.net/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MTQ3ODM1fQ.CJ7dWoN9_M9ZhKBqn9xQx7UNe0qf3Tx3j3d0b-62zic
###
GET https://restaurant-mngt.azurewebsites.net/states
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs

###-- states with city----
GET https://restaurant-mngt.azurewebsites.net/states-details/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs


###-- user details ----
GET https://restaurant-mngt.azurewebsites.net/user-details/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MjAwMjAyfQ.86lGUv4QTEF-eqSSbIB93MG4SUD0xBI195xSD5MzwGY

###--city----
GET https://restaurant-mngt.azurewebsites.net/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODQwNTY1MH0.45ZZfgHAzBFi0B6EAbNYsJUE16xJfaZ60-xRmPZJ_Hs
